name: Sample CICD yaml, Hello World Yaml

on:
  push:
    branches:
      - main
      - dev
  pull_request:
    branches:
      - staging
    paths-ignore:
      - "README.md"
      - "kubernetes/**"
      - ".doicker-ignore"
    # branches-ignore:
    #   - demo
jobs:
  hello-job:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4
      - name: Print message
        run: echo "Hello From GitHub Actions!!!"
      - name: Read data from a file
        run: cat ./index.html
        
